version: '2'

volumes:
  mosquitto-data:
  node-red-data:

services:
  mqtt:
    build: mosquitto
    volumes:
      - 'mosquitto-data:/data'
    ports:
      - '1883:1883'

  node-red:
    build: node-red
    volumes:
      - 'node-red-data:/data'
    ports:
      - '1880:1880'
    depends_on:
      - mqtt
    restart: always
